version: '2.1'

services:

# Wildfyre API Manager

 
  apimanes:
    container_name: apimanes
    image: elasticsearch:5.6.9
    volumes:
      - wf-elastic:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - gwy_net

  apiman:
    container_name: apiman
    image: thorlogic/apiman
    depends_on:
      - apimanes
    links:
      - apimanes
    environment:
      - apiman.es.host=apimanes
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - tomcat-log-volume:/usr/local/tomcat/logs
    networks:
      - gwy_net

# Data Load imports a set of sample data into the reference implementation (optional)




volumes:
  tomcat-log-volume:
  tie-log-volume:
  wf-elastic:
  sqlvol:
  sfs-postgres :

networks:
  gwy_net:
    driver: bridge

